apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:kfJSYF93VWjQSdUcAVj9Cn/bp6Qds64=,iv:byPUTZWNGHm+tz0e0AEqqa/V74BhLFTfdaQrkkEqc4E=,tag:g3esVXdMgJ5dgu7HRkeyBQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:4NRuK1AeJ0W91PB01iW2gmzvOaWbswlqRQ0lvuHnhnFAN8ToXA==,iv:CzlkB0IHbzZJ/e0gYRTpn7mTxWFBeZ/kqj4xe2huu94=,tag:PDEpqiBNBUXwMyTP37+THw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:5PuqNSX+9BhFCM0ZH9rS5mVVX160dXQ=,iv:Q0a2yUl8lY0kMZJxWW1TO3czhUDdA5CWLy+trqtHXfQ=,tag:LUdml6cEbrbzVseXtWMsag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jpdx4yqxg6msjm9pcvhxdp0ld23g3ad8ftqc80ddr29xlrv6fe7scqayfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWjFsTFQ1TWF1NTJ6SHF2
            cnJFWExQaCtxNFBNblpPQ2JjVUtuQkNsVFRnCjJFdTZzSHlMYlZCZFMzcTFZV212
            c0hNMEhoT2hORVI2dWZjaUNJSUhMYmsKLS0tIGRTTFNDbHcrWGZFclk3b203NjZI
            dnVJUG5MemJiU25XalBpZXA5TmtWQUEKOwWEGa924ipZdlrFbP3hBhtBjKUNq3FG
            xa1F/hImrpGoynir+xLmMoeReLQI8Ghjfbz4zB7P0u0gd6kiQ1ZU1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-09T17:20:15Z"
    mac: ENC[AES256_GCM,data:2EPNXDFS6YdUbVENh1HXanhg+kmjBfcVBwHoUMsMfD3ZvzQQx6+vEiZaiiZcxxN2bfoEGvN680mxbWBypXkON48FtuO+sKlTyhixZrxQmXAcG0rSlif2CLvD/+GaiwDse7+YL+NIiSfTPM6vg6IVYjHv+Jl1Ug6NFJ9tFAuCrUg=,iv:hWezyNuulZXx69RXUo59rWwH7mRGqXRhJScU8Fn3SO8=,tag:XTUK2HWhfaFCBW8QXVbkkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
