apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:4OAf7Vc0K5VNCzwKb433RkpE/s7Qye2KgUXNWChpRMLPFfsO6g==,iv:vd7dDn0g1wUB239EDuqGxGBoBDsb2s1JpDEjKYDR9wM=,tag:5pouSJjRe29jcWawD6r/xQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jpdx4yqxg6msjm9pcvhxdp0ld23g3ad8ftqc80ddr29xlrv6fe7scqayfd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRlZFdzIrVm9VUzVpVHRO
            MlAzSmlnWWl2ajhEdFVNUVRYL1V2R1gxR0F3ClR4bzY4b0tSc0w3dXFFR2xNWjRL
            MVcrZEdzeDZ4clQ2WUZrUVJqMVR3c1kKLS0tIGxjZmJiWFlvQk1JM0VJaURIc0Fh
            b1N4WDFCZW1ZdVFDMUNIZGpyQ2ttd2cKH7blrZmZDF4T9FXjhneD1IBobrN0j/ot
            oFMITwYDR6sqRSUvPLnBrqe1+Nc+t2xdr5OUfLGuumGSErl2eyyf4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-09T17:20:15Z"
    mac: ENC[AES256_GCM,data:I809hhhxtWHLUBc+1yWG3U7WGJy2IVlYhr+yPRppAzUkzA58j59Qi9eglqF6NmyJwfRxKS9D+Kx6EOEGES2IJzjpitwJeJb29hM5rzx7nCh27VIqMdzHYI8DH5NyHHOtqzT1Reze/ZVxfpGnVzLlyIhqKtgWD1pSbEpBA1eIy0Q=,iv:vOAojnEmTW9VLB5oS3yW0dxM4wxRPiosaFfTGWbs06I=,tag:QzKHtCjjeMq0WLTuPWesKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
